#pragma once

#include <qglobal.h>
#include <qnamespace.h>
#include <qfontdatabase.h>
#include <qnetworkreply.h>
#include <qobjectdefs.h>
#include <qpixmap.h>
#include <qpushbutton.h>
#include <qguiapplication.h>
#include <qcheckbox.h>
#include <QHBoxLayout>
#include <qlabel.h>
#include <QtNetwork/QNetworkAccessManager>
#include <qsize.h>
#include <qsizepolicy.h>
#include <qstringview.h>
#include <QtNetwork/QNetworkReply>
#include <QImageReader>
#include <QSystemTrayIcon>
#include <qsystemtrayicon.h>
#include <qscrollbar.h>
#include <QtNetwork/qnetworkaccessmanager.h>
#include <QtNetwork/qnetworkrequest.h>
#include <QFileDialog>
#include <QProcess>
#include <QWebEngineView>
#include <QWebEngineProfile>
#include <QStandardPaths>
